name: Update release on release

on: workflow_dispatch

# working as expected with on triggered release
# release:
#   types: [created]

jobs:
  run_script:
    name: Run script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Running script
        run: npm run hi
      - name: Write output to github job
        run: echo '${{ steps.hi.summary }}' >> $GITHUB_STEP_SUMMARY
