name: Update release on release

on: workflow_dispatch

# working as expected with on triggered release
# release:
#   types: [created]

jobs:
  run_script:
    name: Run script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Running script
        id: script
        run: |
          OUTPUT=$(node ./scripts/update-release.js)
          echo "::set-output name=scriptOutput::$OUTPUT"
      - name: Echo output to github suummary
        run: echo "${{ steps.script.outputs.scriptOutput }}" >> $GITHUB_STEP_SUMMARY
