name: Update release on release

on: workflow_dispatch

# working as expected with on triggered release
# release:
#   types: [created]

jobs:
  run_script:
    name: Run script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: hi
        run: npm run hi
      - name: Write output to github job
        run: echo '${{ steps.hi.summary }}' >> $GITHUB_STEP_SUMMARY
      - name: Set color
        id: color-selector
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"
